copyright = "© Kendra Plante"
defaultContentLanguage = "en"
disableKinds = ["taxonomy"]
enableRobotsTXT = true
languageCode = "en"
timeZone = "US/Eastern"
timeout = "120s"
title = "Kendra Plante Photography"
theme = ["gallery"]

[params]
  defaultTheme = "dark"
  description = "Photography portfolio for Kendra Plante Photography"
  title = "Kendra Plante Photography"
  [params.author]
    email = "kendra@kendraplantephotography.com"
    name = "Kendra Plante"
  [params.socialIcons]
    instagram = "https://instagram.com/kendraplantephotography"
    email = "mailto:kendra@kendraplantephotography.com"
    website = "https://kplante.com"
    #mastodon = "https://example.com"
    #pixelfed = "https://example.com"
    #mixcloud = "https://example.com"
    #flickr = "https://www.flickr.com"
    #500px = "https://500px"
  [params.gallery]
    #boxSpacing = 10
    #targetRowHeight = 288
    #targetRowHeightTolerance = 0.25

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML"]
  section = ["HTML"]

[imaging]
  quality = 75
  resampleFilter = "CatmullRom"
  [imaging.exif]
    disableDate = false
    disableLatLong = true
    includeFields = "ImageDescription|Orientation"

#[module]
#  [module.hugoVersion]
#    min = "0.121.2"
#  [[module.imports]]
#    path = "github.com/nicokaiser/hugo-theme-gallery/v4"

[menu]
  [[menu.footer]]
    name = "GitHub"
    url = "https://github.com/nicokaiser/hugo-theme-gallery/"
    weight = 3

[services]
  [services.rss]
    limit = 100
